"""Shared fixtures for hermes-base tests.

Integration tests (`pytest -m integration`) load wire-dev env from
`agents-runtime/.env.dev.local` (generated by `./scripts/wire-dev.sh env`).
Requires `./scripts/wire-dev.sh up` so Postgres/Redis port-forwards are active.
"""

from __future__ import annotations

import os
import uuid
from collections.abc import AsyncIterator
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[3]
WIRE_DEV_ENV = REPO_ROOT / ".env.dev.local"
KIND = "agent"


def _parse_env_file(path: Path) -> dict[str, str]:
    if not path.is_file():
        return {}
    out: dict[str, str] = {}
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line[len("export ") :]
        if "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] == '"':
            value = bytes(value[1:-1], "utf-8").decode("unicode_escape")
        out[key] = value
    return out


def _wire_dev_dsn() -> str | None:
    env = {**_parse_env_file(WIRE_DEV_ENV), **os.environ}
    dsn = env.get("VFS_DSN") or env.get("POSTGRES_DSN", "")
    if not dsn:
        return None
    return dsn.replace("postgresql+asyncpg://", "postgresql://")


def _wire_dev_session_dsn() -> str | None:
    env = {**_parse_env_file(WIRE_DEV_ENV), **os.environ}
    dsn = env.get("HERMES_SESSION_DSN") or env.get("VFS_DSN") or env.get("POSTGRES_DSN", "")
    if not dsn:
        return None
    return dsn.replace("postgresql+asyncpg://", "postgresql://")


@pytest.fixture(scope="session")
def wire_dev_env() -> dict[str, str]:
    """Merge `.env.dev.local` into os.environ for the test session."""
    loaded = _parse_env_file(WIRE_DEV_ENV)
    if loaded:
        os.environ.update(loaded)
    return loaded


@pytest.fixture()
async def vfs_pool(wire_dev_env: dict[str, str]) -> AsyncIterator[object]:
    from runtime_common.vfs.store import create_asyncpg_pool

    dsn = _wire_dev_dsn()
    if not dsn:
        pytest.skip(
            "VFS_DSN unset — run: ./scripts/wire-dev.sh up && ./scripts/wire-dev.sh env"
        )
    try:
        pool = await create_asyncpg_pool(dsn, min_size=1, max_size=4)
        async with pool.acquire() as conn:
            await conn.fetchval("SELECT 1")
    except OSError as exc:
        pytest.skip(f"wire-dev Postgres unreachable ({dsn}): {exc}")
    except Exception as exc:  # noqa: BLE001 — skip when cluster DB not wired
        pytest.skip(f"wire-dev Postgres connect failed: {exc}")

    yield pool
    await pool.close()


@pytest.fixture()
async def vfs_store(vfs_pool: object):
    from runtime_common.vfs.store import AsyncpgAgentVfsStore

    return AsyncpgAgentVfsStore(vfs_pool)


@pytest.fixture()
def wire_session_dsn(wire_dev_env: dict[str, str]) -> str:
    dsn = _wire_dev_session_dsn()
    if not dsn:
        pytest.skip("HERMES_SESSION_DSN unset — run ./scripts/wire-dev.sh env")
    return dsn


@pytest.fixture()
def wire_agent_name() -> str:
    """Unique VFS agent scope per test — avoids clobbering dev registrations."""
    suffix = uuid.uuid4().hex[:12]
    return f"hermes-wire-{suffix}"


@pytest.fixture()
async def cleanup_wire_agent(vfs_store, wire_agent_name: str):
    yield
    pattern = "/profile/**"
    try:
        paths = await vfs_store.glob(KIND, wire_agent_name, pattern)
        for path in paths:
            await vfs_store.delete(KIND, wire_agent_name, path)
    except Exception:
        pass
