apiVersion: v1
kind: ConfigMap
metadata:
  name: garage-config
  namespace: garage
data:
  garage.toml: |
    metadata_dir = "/var/lib/garage/meta"
    data_dir = "/var/lib/garage/data"
    db_engine = "sqlite"
    replication_factor = 1
    metadata_auto_snapshot_interval = "6h"

    rpc_bind_addr = "[::]:3901"
    rpc_public_addr = "garage-0.garage-headless.garage.svc.cluster.local:3901"

    [s3_api]
    s3_region = "garage"
    api_bind_addr = "[::]:3900"
    root_domain = ".s3.garage.local"

    [s3_web]
    bind_addr = "[::]:3902"
    root_domain = ".web.garage.local"
    index = "index.html"

    [admin]
    api_bind_addr = "[::]:3903"
